# Generated by Django 3.1.4 on 2021-03-09 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="following",
            field=models.ManyToManyField(related_name="followers", to=settings.AUTH_USER_MODEL),
        ),
    ]
