# Generated by Django 3.1.4 on 2021-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210323_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
