# Generated by Django 3.1.4 on 2021-04-22 15:12

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_citext_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
