# Generated by Django 3.1.4 on 2021-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210423_2302'),
    ]

    operations = [
        migrations.RunSQL('update users_player set display_name=null'),
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
