# Generated by Django 3.1.4 on 2021-07-15 20:48

from django.db import migrations, models


def clear_none_referrer(apps, schema_editor):
    Player = apps.get_model("users", "Player")
    qs = Player.objects.filter(referrer="none").all()
    for p in qs:
        p.referrer = None
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20210506_1414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(clear_none_referrer, reverse_code=migrations.RunPython.noop),
    ]
