# Generated by Django 3.1.4 on 2021-07-19 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def player_fix(apps, schema_editor):
    Player = apps.get_model("users", "Player")

    for p in Player.objects.all():
        try:
            r = Player.objects.filter(email=p.referrer).get()
            p.referrer_player = r
            p.save()
        except Player.DoesNotExist:
            if p.referrer:
                print(f"Cannot find player record for {p.referrer}")


def pending_fix(apps, schema_editor):
    Player = apps.get_model("users", "Player")
    PendingEmail = apps.get_model("users", "PendingEmail")

    for p in PendingEmail.objects.all():
        if p.referrer:
            try:
                r = Player.objects.filter(email=p.referrer).get()
                p.referrer_player = r
                p.save()
            except Player.DoesNotExist:
                print(f"Cannot find player record for {p.referrer}")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20210715_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingemail",
            name="referrer_player",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="referrer_player",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(pending_fix),
        migrations.RunPython(player_fix),
        migrations.RemoveField(
            model_name="pendingemail",
            name="referrer",
        ),
        migrations.RemoveField(
            model_name="player",
            name="referrer",
        ),
        migrations.RenameField(
            model_name="pendingemail",
            old_name="referrer_player",
            new_name="referrer",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="referrer_player",
            new_name="referrer",
        ),
    ]
