# Generated by Django 3.1.4 on 2021-07-22 12:16

from django.db import migrations, models
import users.models
import secrets

'''
Warning: When you create a field and migrate an existing database the function will run 
         only once and updates with the same 'random' number. If you already have 500 
         entries in the model. You will have the same string, say '548945', for every record.
'''


def fix(apps, schema_editor):
    player = apps.get_model('users', 'Player')
    for p in player.objects.all():
        flag = True
        while flag:
            code = secrets.token_urlsafe()[:5]
            if not player.objects.filter(code=code).exists():
                p.code = code
                p.save()
                flag = False


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210719_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.RunPython(fix),
        migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(db_index=True, default=users.models.create_code, max_length=5, unique=True),
        ),
    ]
