# Generated by Django 3.1.4 on 2021-07-23 15:13

from django.db import migrations
from users.models import Player


def fix(apps, schema_editor):
    # comment this out because it no longer works with new migrations.
    pass
    # for p in Player.objects.all():
    #     # save will set unique codes
    #     p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_player_code"),
    ]

    operations = [
        migrations.RunPython(fix),
    ]
