# Generated by Django 3.1.4 on 2021-07-23 15:13

from django.db import migrations

import secrets

def fix(apps, schema_editor):
    player = apps.get_model('users', 'Player')
    for p in player.objects.all():
        flag = True
        while flag:
            code = secrets.token_urlsafe()[:5]
            p.code = code
            try:
                p.save()
                flag = False
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_player_code'),
    ]

    operations = [
        migrations.RunPython(fix),
   ]
