# Generated by Django 3.1.4 on 2021-07-23 15:13

from django.db import migrations, models
from users.models import code_player


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_data'),
    ]

    operations = [
       migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(db_index=True, max_length=5, unique=True, default=code_player),
        ),

    ]
