# Generated by Django 3.1.4 on 2021-09-14 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.player',),
        ),
    ]
