# Generated by Django 3.2.8 on 2022-01-07 15:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_player_referrer"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="data",
            field=models.JSONField(default=users.models.default_data_dict),
        ),
    ]
