repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        name: "Don't commit to master branch"
        args: ["--branch=master"]

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
