# Generated by Django 3.1.4 on 2021-06-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created",)},
        ),
    ]
