# Generated by Django 3.2.8 on 2022-01-04 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="winners",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="games_won", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
