# Generated by Django 3.2.8 on 2022-02-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_playerrankscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='winners',
        ),
    ]
