# Generated by Django 3.2.8 on 2022-04-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_leaderboardmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerrankscore',
            options={'ordering': ('leaderboard__game__game_id',)},
        ),
    ]
