# Generated by Django 3.1.4 on 2021-09-03 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_player_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAddress',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.player')),
                ('Full Name', models.CharField(max_length=128)),
                ('Address line 1', models.CharField(max_length=128)),
                ('Address line 2', models.CharField(blank=True, max_length=128)),
                ('City', models.CharField(max_length=128)),
                ('State', models.CharField(max_length=2)),
                ('ZIP / Postal code', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(default='First edition coffee mug', help_text='ex. Coffee mug', max_length=150)),
                ('Claim date', models.DateField(auto_now=True)),
                ('Sent date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'reward')},
            },
        ),
    ]
