# Generated by Django 3.1.4 on 2021-10-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="claim_date",
            field=models.DateField(auto_now_add=True, verbose_name="Claim date"),
        ),
    ]
