# Generated by Django 3.1.4 on 2021-04-28 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("player", "question")},
        ),
    ]
