# Generated by Django 3.1.4 on 2021-04-30 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_commonology_series(apps, schema_editor):
    Series = apps.get_model('game', 'Series')
    commonology = Series.objects.create(name="Commonology")
    Player = apps.get_model('users', 'Player')
    for p in Player.objects.all():
        commonology.players.add(p)


def backwards_passthrough(apps, schema_editor):
    # we will just be deleting relations
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20210428_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('hosts', models.ManyToManyField(related_name='hosted_series', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_commonology_series, backwards_passthrough),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.series'),
            preserve_default=False,
        ),
    ]
