# Generated by Django 3.1.4 on 2021-05-06 19:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_auto_20210504_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bottom_commentary",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="top_commentary",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="hide_default_results",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="questions/"),
        ),
        migrations.AddField(
            model_name="question",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("MC", "Multiple Choice"),
                    ("FR", "Free Response"),
                    ("OP", "Optional"),
                    ("OV", "Optional (visible)"),
                ],
                max_length=2,
            ),
        ),
    ]
