# Generated by Django 3.1.4 on 2021-05-11 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('game', '0004_auto_20210506_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='community.thread'),
        ),
    ]
