# Generated by Django 3.1.4 on 2021-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_auto_20210512_0023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_id",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="game",
            unique_together={("series", "game_id")},
        ),
    ]
