# Generated by Django 3.1.4 on 2021-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_question_thread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="google_form_url",
            field=models.CharField(blank=True, help_text="Enter the form url", max_length=255),
        ),
    ]
