# Generated by Django 3.1.4 on 2021-06-30 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_game_unique_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
