# Generated by Django 3.1.4 on 2021-06-09 10:00

import django.contrib.postgres.fields
from django.db import migrations, models


def forwards(apps, schema_editor):
    Question = apps.get_model("game", "Question")
    for q in Question.objects.all():
        if q.type == "MC":
            q.type = "GA"
        q.save()


def backwards(apps, schema_editor):
    Question = apps.get_model("game", "Question")
    for q in Question.objects.all():
        if q.type == "GA":
            q.type = "MC"
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_auto_20210630_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("GA", "Game"), ("OP", "Optional"), ("OV", "Optional (visible)")], max_length=2
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="answer",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
