# Generated by Django 3.1.4 on 2021-04-19 21:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_name", models.CharField(default="Alex Fruin", max_length=150)),
                (
                    "from_email",
                    models.EmailField(
                        default="alex@commonologygame.com", max_length=254, verbose_name="from email address"
                    ),
                ),
                ("test_recipient", models.EmailField(max_length=254, verbose_name="test recipient email address")),
                ("subject", models.CharField(max_length=150)),
                ("message", ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("tested", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
            ],
        ),
    ]
