# Generated by Django 3.1.4 on 2021-04-19 16:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massmailmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='massmailmessage',
            name='subject',
            field=models.CharField(default='foo', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massmailmessage',
            name='test_recipient',
            field=models.EmailField(default='ms@quizitive.com', max_length=254, verbose_name='test recipient email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massmailmessage',
            name='tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='massmailmessage',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
