# Generated by Django 3.1.4 on 2021-04-18 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmailmessage',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
