# Generated by Django 3.1.4 on 2021-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_mailmessage_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailmessage",
            name="categories",
            field=models.CharField(blank=True, help_text="A comma separated list of categories.", max_length=50),
        ),
    ]
