# Generated by Django 3.1.4 on 2021-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210419_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='massmailmessage',
            name='from_email',
            field=models.EmailField(default='concierge@commonologygame.com', max_length=254, verbose_name='test recipient email address'),
        ),
        migrations.AddField(
            model_name='massmailmessage',
            name='from_name',
            field=models.CharField(default='CommonologyGame Concierge', max_length=150),
        ),
    ]
