# Generated by Django 3.1.4 on 2021-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20210419_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmailmessage',
            name='from_email',
            field=models.EmailField(default='alex@commonologygame.com', max_length=254, verbose_name='test recipient email address'),
        ),
        migrations.AlterField(
            model_name='massmailmessage',
            name='from_name',
            field=models.CharField(default='Alex Fruin', max_length=150),
        ),
    ]
