# Generated by Django 3.1.4 on 2021-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0011_auto_20210816_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailmessage",
            name="components",
            field=models.ManyToManyField(blank=True, related_name="messages", to="mail.Component"),
        ),
    ]
