# Generated by Django 3.2.8 on 2022-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0018_auto_20211121_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='scheduled',
            field=models.DateTimeField(blank=True, help_text='If set then mail will go out at the scheduled time.', null=True),
        ),
    ]
