name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: commonology
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PEP8
        run:
          pycodestyle --config=./setup.cfg .

      - name: Celery
        env:
          EAGER_CELERY: True
        run: celery -A project  worker -E -l DEBUG &

      - name: Integration Tests
        env:
          GITHUB_COMMONOLOGY_CI_TEST: True
          EAGER_CELERY: True
          API_KEY: ${{secrets.API_KEY}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          TEST_CLIENT_PW: ${{secrets.TEST_CLIENT_PW}}

        run: python manage.py migrate && python manage.py test
